### ISSUE TITLE
HTCC-AB02 pinout diagram suffers from same problem as original HTCC-AB01 pinout diagram

### ISSUE THREAD

**Issue by lnlp** [HelTecAutomation/ASR650x-Arduino#95]
As the pinout diagram resource is external to GitHub, but relevant to both this repository and https://github.com/HelTecAutomation/HeltecDocs, I add it as an issue here.

 The [HTCC-AB02 pinout diagram](https://resource.heltec.cn/download/CubeCell/HTCC-AB02/HTCC-AB02_PinoutDiagram.pdf) suffers from the same problem as the original HTCC-AB01 pinout diagram and should be fixed _(for HTCC-AB01 it was fixed already)_.

For a description of the issue and it's importance see issue #55. The HTCC-AB02 pinout diagram suffers from the same problem.

**Comment by wasn-eu** [comment]
fixed

**Comment by lnlp** [comment]
@wasn-eu 
> fixed

No, this has not been fixed yet.

**Comment by wasn-eu** [comment]
There are now the mentilned red lines showing the position of the pins.
If that is not what you thought of please explain

**Comment by lnlp** [comment]
Please see #55 discussions for a description.

I still see this pinout diagram for HTCC-AB02:

![capture 2020-05-07 14·46·56](https://user-images.githubusercontent.com/40600181/81296250-e7083380-9071-11ea-80fd-6470c7adbaee.png)

While I expect something similar to this: Check and compare the **positions** of the GPIO/pin number**labels** and red lines for the User Control and VExt pins:

![capture 2020-05-07 14·51·30](https://user-images.githubusercontent.com/40600181/81296567-5da53100-9072-11ea-9678-a0044a93ed9a.png)

Last image is from current HTCC-AB01 pinout (which was previously corrected),
which uses different GPIO and pin numbers. This image is just used for an example.

**Comment by wasn-eu** [comment]
If i open

https://resource.heltec.cn/download/CubeCell/HTCC-AB02/HTCC-AB02_PinoutDiagram.pdf

There are red lines for those pins

**Comment by lnlp** [comment]
Please _carefully_ read my above responses and all responses in issue #55 _again_.

It _**very clearly**_ describes the issue and the pictures very clerly describe the issue.

Apparently many details of above responses get lost in English to Chinese translation?
The pictures are not translated and also clearly show the issue.

**Comment by wasn-eu** [comment]
please stay calm, no need to get rude.

for people used to read those sheets everyday this is clear, but i fully understand that there is a potential for missunderstanding.

you only want to separate the labels for those pins with red lines from the other labels?

I will reopen the issue but we have to wait for somebody from heltec to change it because i dont have the rights to change it on the website.

**Comment by lnlp** [comment]
I _am_ calm and I am not rude.

Thanks for reopening.

Yes there is a big potential for missunderstanding, included for people used to reading such pinouts. 

This was already clearly addressed in issue #55 but then for HTCC-AB01.
The same problem is now repeated in pinout for HTCC-AB02, which I don't understand because one should have learned from #55 how not to do it.

**Comment by wasn-eu** [comment]
do you think this version is better:
![image](https://user-images.githubusercontent.com/6542516/81434598-b655f600-9166-11ea-9f97-8041943dd682.png)

**Comment by lnlp** [comment]
Yes, much better.

**Comment by wasn-eu** [comment]
That was only a quick photoshop fix.
@Heltec-Aaron-Lee please make this changes in the PDF
